language: python
python:
    - "2.7"
install:
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install pytest"
    - "pip install pytest-cov"
    - "pip install coverage"
    - "pip install coveralls"
script:
    - "coverage run --source=tornado_json setup.py test"
after_success:
    coveralls
